Part 2
samyou-softwire/nasa pull request #2
Opened 2023-10-23 09:24 UTC by samyou-softwire

2023-10-23 16:50 UTC, kwunkiuma requested changes
Looking good! Just some very minor nitpicks 😄

2023-10-23 16:50 UTC, kwunkiuma commented on src/rovers.ts
> +        const response: AxiosResponse<Welcome, any> = await axios.get(
I think we can simplify this just a bit using `axios.get<Welcome>` 🙂

2023-10-23 16:50 UTC, kwunkiuma commented on src/server.ts
> +config();
I'm not sure we need this in this file?

2023-10-24 08:56 UTC, samyou-softwire commented on src/server.ts
> +config();
nope 👍

2023-10-24 09:00 UTC, samyou-softwire commented on src/rovers.ts
> +        const response: AxiosResponse<Welcome, any> = await axios.get(
yep 👍

2023-10-24 09:10 UTC, kwunkiuma approved these changes
LGTM, thanks!

2023-10-24 10:30 UTC, merged